// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCseCyIegQQEbF58aYPT8iT9akofV_wHx4',
    appId: '1:387514189783:web:70daa42d9423eabab32d92',
    messagingSenderId: '387514189783',
    projectId: 'ddlib-87f45',
    authDomain: 'ddlib-87f45.firebaseapp.com',
    storageBucket: 'ddlib-87f45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQuDqH1gNw0s9Jir-0ohzVhhbZVcDcmjU',
    appId: '1:387514189783:android:9a54ed853c6c7827b32d92',
    messagingSenderId: '387514189783',
    projectId: 'ddlib-87f45',
    storageBucket: 'ddlib-87f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFpw69Rp8lFlkgSKZ0mrSDfl0D8hfweH4',
    appId: '1:387514189783:ios:c3643c2f80d74d75b32d92',
    messagingSenderId: '387514189783',
    projectId: 'ddlib-87f45',
    storageBucket: 'ddlib-87f45.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVKMWIXMfJxH9FZXGwNb-0xWI7kYuxzjk',
    appId: '1:462191290750:ios:92914a010812782c6cab2f',
    messagingSenderId: '462191290750',
    projectId: 'library-cool-projecy',
    storageBucket: 'library-cool-projecy.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrFNNUUi64ymtGbEw123BWuJZiK6hU1-Y',
    appId: '1:462191290750:web:96a1f0b74e3aee9c6cab2f',
    messagingSenderId: '462191290750',
    projectId: 'library-cool-projecy',
    authDomain: 'library-cool-projecy.firebaseapp.com',
    storageBucket: 'library-cool-projecy.appspot.com',
  );

}